[general]
import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/host.toml",
]

[font.normal]
# family = "MartianMono Nerd Font"
family = "GeistMono Nerd Font"

[window]
blur = true
startup_mode = "Maximized"
