[general]
import = [
    "~/.config/alacritty/colors.toml",
    "~/.config/alacritty/host.toml",
]

[font.normal]
# family = "GeistMono Nerd Font"
family = "ShureTechMono Nerd Font"

[window]
startup_mode = "Maximized"
