#
# ~/.bash_profile
#

[[ -d "$HOME/.cargo" ]] && [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
[[ -f "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"

export PATH=~/.local/bin/:$PATH
export PATH=~/bin/:$PATH
export EDITOR="nvim"
export VISUAL="nvim"
export BROWSER="brave"
export PAGER="nvim +Man!"

[[ -f ~/.bashrc ]] && . ~/.bashrc

